### ISSUE TITLE
Choosing instructors

### ISSUE THREAD

**Issue by mtorpey** [StAResComp/2018-11-27-standrews#1]
Hi all,

@alex-konovalov suggested (perhaps sensibly) that we should move the discussion of instructors from email to issues, to spare his inbox – so here we are.

The schedule Alex suggested is as follows:
* Day 1 morning shell, afternoon Python 1
* Day 2 morning Git, afternoon Python 2

Alex also suggested that Isla take a small section of the shell lesson, and I take a small section of the Git lesson.  This seems like a great idea to me, and I'm happy to act as helper for the rest of the time.

As for the rest of the instruction, it seems from the email thread that we were moving towards:
* Shell: Paddy
* Python 1: Peter Cock
* Git: Alex
* Python 2: Leighton

but I don't think we absolutely settled on that.

**Comment by peterjc** [comment]
https://starescomp.github.io/2018-11-27-standrews/

* Day one being Tuesday 27 Nov 2018 (Paddy & Peter)
* Day two being Wednesday 28 Nov 2018 (Alex & Leighton)

That schedule should be fine for me 👍
